<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "regg";

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // $ice = $_POST['ice'];
    $term = "term 1";

    $selclass = "SELECT class FROM class";
    $classres = mysqli_query($conn,$selclass);
    $classes = [];
    while ($rok = mysqli_fetch_assoc($classres)) {
        $classes[] = $rok['class'];
    }

    foreach($classes as $class){
        $class = $class;
        // echo $class;
        $classif = mysqli_fetch_assoc(mysqli_query($conn , "SELECT id FROM class WHERE class='$class'"))['id'];
        $selstudent = "SELECT id FROM students WHERE classid='$classif'";
        $studentres = mysqli_query($conn , $selstudent);
        $ice = [];
        while ($roh = mysqli_fetch_assoc($studentres)) {
            $ice[] = $roh['id'];
        }

    }

    // $class = "S1C";
    // $ice = array("155" , "156");
    // $classif = "200";


    require('fpdf.php');

    class MyPDF extends FPDF {
        function header() {
            $this->Image('logo2.jpg', 10, 10, 30, 30);
        }

        function footer() {
            $this->Ln();
            $this->SetFont('Times', 'i', 12);
            $this->Text(11, 285, '_______________________');
            $this->Text(12, 290, 'Class Teacher signature', 0, 0, 'L');
            $this->Text(150, 290, 'Headmaster signature', 0, 0, 'C');
            $this->Text(150, 285, '_______________________');
            $this->SetFont('Times', 'i', 10);
            $this->Text(150, 295, 'Generated by School coding club');
        }


        function generateReport($class, $term, $ice, $conn) {

            //TERM 1 REPORT --------------------------------------------------
            if($term === "term 1"){
                foreach($ice as $item){
                    $sql = "SELECT * FROM marks WHERE class LIKE '%$class%'  AND stid='$item'/*AND term LIKE '%$term%' */ GROUP BY fname ORDER BY SUM(cat11 + ex1) DESC";
                    $result = $conn->query($sql);
        
                    $query = "SELECT * FROM students WHERE class = '$class' AND id = '$item' ";
                    $res = mysqli_query( $conn , $query );
                    $rowa = mysqli_fetch_assoc($res);
                    $ros = mysqli_num_rows($res);
                    $photo = "deafault.png";
        
                    if (!$result) {
                        die("Query failed: " . $conn->error);
                    }

                    // $toto = count($rowa);

                while ($row = mysqli_fetch_assoc($result)) {
                    $this->AddPage('P', 'A4', 0);

                    if($photo=='default.png'){
                        $this->SetFont('Times', 'B', 14);
                        $this->Cell(160, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                        $this->Cell(-24, 5, 'Class :', 0, 0, 'R');
                        $this->SetFont('Times', 'I', 14);
                        $this->Cell(80, 5, $class, 0, 0, 'L');
                        $this->Ln();

                        $this->SetFont('Times', 'B', 14);
                        $this->Cell(160, 8, 'ES KANOMBE', 0, 0, 'C');
                        $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                        $this->SetFont('Times', 'I', 12);
                        $this->Cell(80, 8, $term, 0, 0, 'L');
                        $this->Ln();

                        $this->SetFont('Times', 'B', 14);
                        $this->Cell(160, 8, 'Tel: 0788875779', 0, 0, 'C');
                        $this->SetFont('Times', 'B', 14);
                        $this->Cell(-5, 8, 'Student name :', 0, 0, 'R');
                        $this->SetFont('Times', 'I', 14);
                        $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                        $this->Ln();

                        $fname = $row["fname"];
                        $ide = $row["stid"];

                        $this->SetFont('Times', 'B', 13);
                        $this->Cell(160, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                        $this->SetFont('Times', 'B', 14);
                        $this->Cell(8, 8, 'Student reg number :', 0, 0, 'R');
                        $this->SetFont('Times', 'I', 14);
                        $this->Cell(80, 8, ($item), 0, 0, 'L');
                        $this->Ln();
                        $this->Ln();
                    }

                    else{
                        $this->Image('passports/'.$rowa['dir'], 170, 10, 30, 30);
                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(130, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                        $this->SetTextColor('0','0','0');
                        $this->Cell(-23, 5, 'Class :', 0, 0, 'R');
                        $this->SetFont('Times', '', 10);
                        $this->Cell(80, 5, $class, 0, 0, 'L');
                        $this->Ln();
    
                        $this->SetTextColor('0','0','0');
                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(130, 8, 'ES KANOMBE', 0, 0, 'C');
                        $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                        $this->SetFont('Times', '', 10);
                        $this->Cell(50, 8, $term, 0, 0, 'L');
                        $this->Ln();
    
                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(130, 8, 'Tel: 0788875779', 0, 0, 'C');
                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(-10, 8, 'Student name :', 0, 0, 'R');
                        $this->SetFont('Times', '', 10);
                        $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                        $this->Ln();

                        $fname = $row["fname"];
                        $ide = $row["stid"];

                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(130, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                        $this->SetFont('Times', 'B', 10);
                        $this->Cell(-1, 8, 'Student reg number :', 0, 0, 'R');
                        $this->SetFont('Times', '', 10);
                        $this->Cell(50, 8, ($item), 0, 0, 'L');
                        $this->Ln();
                        $this->Ln();
                    }

                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(190, 10, "STUDENT'S 1'ST TERM REPORT", 1, 0, 'C');
                    $this->Ln();
                    $this->Ln();

                    $this->SetFont('Times', 'B', 12);
                    $this->Cell(96, 8, 'TOTAL', 1, 0, 'C');
                    $this->Cell(94, 8, ' TERM 1 ', 1, 0, 'C');

                    $this->Ln();

                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(51, 8, 'SUBJECTS', 1, 0, 'C');
                    $this->Cell(15, 8, ' CAT ', 1, 0, 'C');
                    $this->Cell(15, 8, ' EX ', 1, 0, 'C');
                    $this->Cell(15, 8, ' TOT ', 1, 0, 'C');
                    $this->Cell(31, 8, ' CAT1 ', 1, 0, 'C');
                    $this->Cell(31, 8, ' EX1 ', 1, 0, 'C');
                    $this->Cell(32, 8, ' TOT1 ', 1, 0, 'C');

                    $this->Ln();

                    $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid ='$ide' ORDER BY outof DESC";
                    $resultm = $conn->query($sqlm);

                    $totale1 = 0;
                    $totale2 = 0;
                    $totale1a = 0;
                    $totale2a = 0;
                    $totale1b = 0;
                    $totale2b = 0;
                    $totale1c = 0;
                    $totale2c = 0;
                    $step11 = 0;
                    $step1 = 0;
                    
                    $emergency = "SELECT id FROM class WHERE class='$class' ";
                    $classid = mysqli_fetch_assoc(mysqli_query($conn , $emergency))['id'];
                    
                    // echo $classid;

                    $funn = "SELECT * FROM assessments WHERE class='$class' AND classid='$classid' ";
                    $funn1 = $conn->query($funn);
                    $fun2 = mysqli_fetch_array($funn1);

                    while(($fun1 = mysqli_fetch_assoc($funn1))){
                        $totale1 = $totale1 + $fun1["outof"];
                        $totale2 = $totale2 + $fun1["outof"];
                    }

                    $max = $totale1 + $totale2;

                    while ($rowm = mysqli_fetch_assoc($resultm)) {
                        $subj = $rowm['subject'];
                        $sub = "SELECT cat11, ex1 , cat22, ex2, cat33, ex3, outof FROM assessments WHERE subject ='$subj'";
                        $get = $conn->query($sub);
                        $subq = mysqli_fetch_assoc($get);
                        $outof = $subq['outof'];
                        $cat11 = $subq['cat11'];
                        $ex1 = $subq['ex1'];
                        // $cat22 = $subq['cat22'];
                        // $ex2 = $subq['ex2'];
                        // $cat33 = $subq['cat33'];
                        // $ex3 = $subq['ex3'];

                        $this->SetFont('Times', 'B', 13);
                        $this->Cell(51, 6, ($rowm["subject"]), 1, 0, 'L');
                        $this->Cell(15, 6, (($rowm["outof"])), 1, 0, 'C');
                        $this->Cell(15, 6, ($rowm["outof"]), 1, 0, 'C');
                        $this->Cell(15, 6, ($rowm["outof"] + $rowm["outof"]), 1, 0, 'C');
                        $this->SetFont('Times', '', 12);

                        //term 1
                        if(($rowm["cat11"]/$cat11) < 0.5){
                            $this->SetTextColor('255','0','0');
                            $this->Cell(31, 6, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                            $this->SetTextColor('0','0','0');
                        }
                        else{
                            $this->SetTextColor('0','0','0');
                            $this->Cell(31, 6, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                            $this->SetTextColor('0','0','0');
                        }
                        if(($rowm["ex1"]  /$ex1  ) < 0.5){
                            $this->SetTextColor('255','0','0');
                            $this->Cell(31, 6, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                            $this->SetTextColor('0','0','0');
                        }
                        else{
                            $this->SetTextColor('0','0','0');
                            $this->Cell(31, 6, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                            $this->SetTextColor('0','0','0');
                        }
                        if((($rowm["cat11"]/$cat11)+($rowm["ex1"]  /($ex1+$cat11)  )) <1){
                            $this->SetTextColor('255','0','0');
                            $this->Cell(32, 6, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C'); 
                            $this->SetTextColor('0','0','0');
                        }
                        else{
                            $this->SetTextColor('0','0','0');
                            $this->Cell(32, 6, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C');                             
                            $this->SetTextColor('0','0','0');
                        }
                        $step1 = $step1 + (($rowm["cat11"]/$cat11)*$outof);
                        $step11 = $step11 + (($rowm["ex1"]/$ex1)*$outof);

                        $this->Ln();
                    }

                    $this->SetFont('Times', 'B', 13);
                    $this->Cell(51, 6, 'Total marks', 1, 0, 'L');

                    $sql_total = "SELECT SUM(cat11 + ex1 + Cat22 + ex2 + cat33 + ex3) as total FROM marks WHERE /*term LIKE '%$term%' AND*/ class LIKE '%$class%' /*AND stid LIKE '%$ide%'*/";
                    $result_total = $conn->query($sql_total);
                    $row_total = mysqli_fetch_assoc($result_total);
                    $total_marks = $row_total['total'];

                    //for making total of assessments for astudent (not converted)
                    $total_annual = "SELECT SUM(cat11) AS total1a , SUM(ex1) AS total1b, SUM(cat22) AS total2a, SUM(ex2) AS total2b, SUM(cat33) AS total3a, SUM(ex3) AS total3b FROM marks WHERE class = '$class' ";
                    $quely = $conn->query($total_annual);
                    $totalrows = mysqli_fetch_assoc($quely);
                    $totals1a = $totalrows['total1a'];
                    $totals1b = $totalrows['total1b'];
                    $totals2a = $totalrows['total2a'];
                    $totals2b = $totalrows['total2b'];
                    $totals3a = $totalrows['total3a'];
                    $totals3b = $totalrows['total3b'];

                    $totale1a = $totale1a + $totals1a;
                    $totale2a = $totale2a + $totals1b;
                    $totale1b = $totale1b + $totals2a;
                    $totale2b = $totale2b + $totals2b;
                    $totale1c = $totale1c + $totals3a;
                    $totale2c = $totale2c + $totals3b;
                    
                    //different from the top ones its for total marks for student in marks table not yet converted
                    $totals_annual = "SELECT SUM(cat11) AS totals1a , SUM(ex1) AS totals1b, SUM(cat22) AS totals2a, SUM(ex2) AS totals2b, SUM(cat33) AS totals3a, SUM(ex3) AS totals3b FROM assessments WHERE class = '$class' ";
                    $queby = $conn->query($totals_annual);
                    $totalrows = mysqli_fetch_assoc($queby);
                    $totalss1a = $totalrows['totals1a'];
                    $totalss1b = $totalrows['totals1b'];
                    $totalss2a = $totalrows['totals2a'];
                    $totalss2b = $totalrows['totals2b'];
                    $totalss3a = $totalrows['totals3a'];
                    $totalss3b = $totalrows['totals3b'];

                    $totalee1a = $totalss1a;
                    $totalee2a = $totalss1b;
                    $totalee1b = $totalss2a;
                    $totalee2b = $totalss2b;
                    $totalee1c = $totalss3a;
                    $totalee2c = $totalss3b;

                    //TOTAL MARKS
                    $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid LIKE '%$ide%' ORDER BY subject DESC";
                    $resultm = $conn->query($sqlm);
                    $rowm = mysqli_fetch_assoc($resultm);

                    $this->Cell(15, 6, $totale1, 1, 0, 'C');
                    $this->Cell(15, 6, $totale2, 1, 0, 'C');
                    $this->Cell(15, 6, ($totale1 + $totale2), 1, 0, 'C');
                    // $this->Cell(10, 8, (round((($totale1a)/($totalee1a))*($totale1))), 1, 0, 'C');
                    if(($step1/$totale1)<5){
                        $this->SetTextColor('255','0','0');
                        $this->cell(31, 6, $step1 ,1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->cell(31, 6, $step1 ,1, 0, 'C');
                    }
                    if(($step11/$totale2)<5){
                        $this->SetTextColor('255','0','0');
                        $this->cell(31, 6, $step11 ,1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->cell(31, 6, $step1 ,1, 0, 'C');
                    }
                    $step111 = $step1 + $step11;
                    if(($step111/$max)<5){
                        $this->SetTextColor('255','0','0');
                        $this->cell(32, 6, $step111 ,1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->cell(32, 6, $step111 ,1, 0, 'C');
                    }

                    $this->Ln();

                    $sel = "SELECT SUM(tot1) as toto FROM assessments WHERE classid=(SELECT id FROM class WHERE class='$class')";
                    $resul = mysqli_fetch_assoc(mysqli_query($conn , $sel))['toto'];

                    $this->Cell(96, 8, 'Percentage', 1, 0, 'L');
                    if(($step111/$resul)<5){
                        $this->SetTextColor('255','0','0');
                        $this->Cell(94, 8, round((($step111/$resul)*100),1).' /100', 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->Cell(94, 8, round((($step111/$max)*100),2).' /100', 1, 0, 'C');
                    }

                    $this->Ln();

                    // term 1 position
                    $sql_position = "SELECT fname, SUM(cat11 + ex1) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total DESC";
                    $result_position = $conn->query($sql_position);

                    $position1 = 1;
                    while ($row_position = mysqli_fetch_assoc($result_position)) {
                        if ($row_position['fname'] == $fname) {
                            break;
                        }
                        $position1++;
                    }

                    $tot_students = "SELECT SUM(count) as count FROM students WHERE class = '$class' ";
                    $dothis = $conn->query($tot_students);
                    $prefinal = mysqli_fetch_assoc($dothis);
                    $final = $prefinal['count'];

                    $this->Cell(96, 8, 'Position', 1, 0, 'L');
                    $this->Cell(94, 8, $position1.' /'. $final, 1, 0, 'C');

                    // $this->ln();
                    // $this->cell(184,8, '', 1, 0, 'C');
                    // $this->ln();

                    //ADDENDA ---
                    // $this->Cell(90, 8, "Class Teacher's Remarks and Signature", 1, 0, 'L');
                    // $this->Cell(94, 8, '', 1, 0, 'C');
                    // $this->ln();

                    // $this->Cell(90, 8, "Parent's Signature", 1, 0, 'L');
                    // $this->Cell(94, 8, '', 1, 0, 'C');
                    // $this->ln();

                    $this->setY(-87);
                    $this->setX(10);
                    $this->Rect(10, 210, 190, 20 );
                    $this->cell(35, 20, 'BEHAVIOUR', 1, 0, 'C');
                    $this->cell(62, 10, 'TOTAL', 1, 0, 'C');
                    $this->cell(93, 10, 'Term I', 1, 0, 'C');
                    $this->setY(-77);
                    $this->setX(45);

                    $pull = "SELECT be1 , be2 , be3 FROM marks WHERE stid = '$item' ";
                    $bisubizo = $conn->query($pull);
                    $each = mysqli_fetch_assoc($bisubizo);
                    $term1 = $each['be1'];
                    $term2 = $each['be2'];
                    $term3 = $each['be3']; 

                    $this->cell(62, 10, '40', 1, 0, 'C');
                    $this->cell(93, 10, $term1, 1, 0, 'C');
                    $this->Ln();
                    $this->setY(-80);
                    $this->setX(15);
                    $this->Rect(10, 235, 190, 40 );
                    $this->Text(20, 247, 'REMARKS');
                    $this->Text(90, 247, 'DATE');
                    $this->SetFont('Times', 'i', 13);
                    $this->Text(75, 255, date("l M jS, Y"));  
                    $this->SetFont('Times', 'b', 13);          
                    $this->Text(140, 247, 'HEADMASTER');
                    $this->SetFont('Times', 'i', 13);
                    $this->Text(127, 255, 'TUMUKUNDE Monica Leonard');
    
                    //DECISION
                    if(($step111/$resul)>0.5){
                        $this->Text(15, 255, 'Maintain your position');
                        $this->Ln();
                    }
                    elseif((($step111/$resul)>0.4)&&(($step111/$max)<0.5)){
                        $this->Text(20, 255, 'Pay attention');
                        $this->Ln();
                    }
                    elseif(($step111/$resul)<0.4){
                        $this->Text(15, 255, 'Hard work please');
                        $this->Ln();
                    }
                }
            }


        //SECOND TERM -------------------------------------


        } elseif($term === "term 2"){
            foreach($ice as $item){
                $sql = "SELECT * FROM marks WHERE class LIKE '%$class%'  AND stid='$item'/*AND term LIKE '%$term%' */ GROUP BY fname ORDER BY SUM(cat22 + ex2) DESC";
                $result = $conn->query($sql);
    
                $query = "SELECT * FROM students WHERE class = '$class' AND id = '$item' ";
                $res = mysqli_query( $conn , $query );
                $rowa = mysqli_fetch_assoc($res);
                $ros = mysqli_num_rows($res);
    
                if (!$result) {
                    die("Query failed: " . $conn->error);
                }

                // $toto = count($rowa);

            while ($row = mysqli_fetch_assoc($result)) {
                $this->AddPage('P', 'A4', 0);

                if($rowa['dir']=='default.png'){
                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(160, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                    $this->Cell(-24, 5, 'Class :', 0, 0, 'R');
                    $this->SetFont('Times', 'I', 14);
                    $this->Cell(80, 5, $class, 0, 0, 'L');
                    $this->Ln();

                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(160, 8, 'ES KANOMBE', 0, 0, 'C');
                    $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                    $this->SetFont('Times', 'I', 12);
                    $this->Cell(80, 8, $term, 0, 0, 'L');
                    $this->Ln();

                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(160, 8, 'Tel: 0788875779', 0, 0, 'C');
                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(-5, 8, 'Student name :', 0, 0, 'R');
                    $this->SetFont('Times', 'I', 14);
                    $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                    $this->Ln();

                    $fname = $row["fname"];
                    $ide = $row["stid"];

                    $this->SetFont('Times', 'B', 13);
                    $this->Cell(160, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                    $this->SetFont('Times', 'B', 14);
                    $this->Cell(8, 8, 'Student reg number :', 0, 0, 'R');
                    $this->SetFont('Times', 'I', 14);
                    $this->Cell(80, 8, ($item), 0, 0, 'L');
                    $this->Ln();
                    $this->Ln();
                }

                else{
                    $this->Image('passports/'.$rowa['dir'], 170, 10, 30, 30);
                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(130, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                    $this->SetTextColor('0','0','0');
                    $this->Cell(-23, 5, 'Class :', 0, 0, 'R');
                    $this->SetFont('Times', '', 10);
                    $this->Cell(80, 5, $class, 0, 0, 'L');
                    $this->Ln();

                    $this->SetTextColor('0','0','0');
                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(130, 8, 'ES KANOMBE', 0, 0, 'C');
                    $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                    $this->SetFont('Times', '', 10);
                    $this->Cell(50, 8, $term, 0, 0, 'L');
                    $this->Ln();

                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(130, 8, 'Tel: 0788875779', 0, 0, 'C');
                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(-10, 8, 'Student name :', 0, 0, 'R');
                    $this->SetFont('Times', '', 10);
                    $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                    $this->Ln();

                    $fname = $row["fname"];
                    $ide = $row["stid"];

                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(130, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                    $this->SetFont('Times', 'B', 10);
                    $this->Cell(-1, 8, 'Student reg number :', 0, 0, 'R');
                    $this->SetFont('Times', '', 10);
                    $this->Cell(50, 8, ($item), 0, 0, 'L');
                    $this->Ln();
                    $this->Ln();
                }

                $this->SetFont('Times', 'B', 14);
                $this->Cell(190, 10, "STUDENT'S ANNUAL REPORT", 1, 0, 'C');
                $this->Ln();
                $this->Ln();

                $this->SetFont('Times', 'B', 12);
                $this->Cell(96, 8, 'TOTAL', 1, 0, 'C');
                $this->Cell(47, 8, ' TERM 1 ', 1, 0, 'C');
                $this->Cell(47, 8, ' TERM 2 ', 1, 0, 'C');

                $this->Ln();

                $this->SetFont('Times', 'B', 10);
                $this->Cell(51, 8, 'SUBJECTS', 1, 0, 'C');
                $this->Cell(15, 8, ' CAT ', 1, 0, 'C');
                $this->Cell(15, 8, ' EX ', 1, 0, 'C');
                $this->Cell(15, 8, ' TOT ', 1, 0, 'C');
                $this->Cell(15, 8, ' CAT1 ', 1, 0, 'C');
                $this->Cell(15, 8, ' EX1 ', 1, 0, 'C');
                $this->Cell(17, 8, ' TOT1 ', 1, 0, 'C');
                $this->Cell(15, 8, ' CAT2 ', 1, 0, 'C');
                $this->Cell(15, 8, ' EX2 ', 1, 0, 'C');
                $this->Cell(17, 8, ' TOT2 ', 1, 0, 'C');

                $this->Ln();

                $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid ='$ide' ORDER BY outof DESC";
                $resultm = $conn->query($sqlm);

                $totale1 = 0;
                $totale2 = 0;
                $totale1a = 0;
                $totale2a = 0;
                $totale1b = 0;
                $totale2b = 0;
                $totale1c = 0;
                $totale2c = 0;
                $step11 = 0;
                $step1 = 0;
                $step22 = 0;
                $step2 = 0;
                
                $funn = "SELECT * FROM assessments WHERE class='$class'/*AND term='$term'*/ ";
                $funn1 = $conn->query($funn);
                $fun2 = mysqli_fetch_array($funn1);

                while(($fun1 = mysqli_fetch_assoc($funn1))>0){
                    $totale1 = $totale1 + $fun1["outof"];
                    $totale2 = $totale2 + $fun1["outof"];
                }

                $max = $totale1 + $totale2;

                while ($rowm = mysqli_fetch_assoc($resultm)) {
                    $subj = $rowm['subject'];
                    $sub = "SELECT cat11, ex1 , cat22, ex2, cat33, ex3, outof FROM assessments WHERE subject ='$subj'";
                    $get = $conn->query($sub);
                    $subq = mysqli_fetch_assoc($get);
                    $outof = $subq['outof'];
                    $cat11 = $subq['cat11'];
                    $ex1 = $subq['ex1'];
                    $cat22 = $subq['cat22'];
                    $ex2 = $subq['ex2'];
                    $cat33 = $subq['cat33'];
                    $ex3 = $subq['ex3'];

                    $this->SetFont('Times', 'B', 13);
                    $this->Cell(51, 8, ($rowm["subject"]), 1, 0, 'L');
                    $this->Cell(15, 8, (($rowm["outof"])), 1, 0, 'C');
                    $this->Cell(15, 8, ($rowm["outof"]), 1, 0, 'C');
                    $this->Cell(15, 8, ($rowm["outof"] + $rowm["outof"]), 1, 0, 'C');
                    $this->SetFont('Times', '', 12);
                    //TERM 1
                    if(($rowm["cat11"]/$cat11) > 0.5){
                        $this->SetTextColor('0','0','0');
                        $this->Cell(15, 8, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('255','0','0');
                        $this->Cell(15, 8, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    if(($rowm["ex1"]  /$ex1  ) < 0.5){
                        $this->SetTextColor('255','0','0');
                        $this->Cell(15, 8, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->Cell(15, 8, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    if((($rowm["cat11"]/$cat11)+($rowm["ex1"]  /$ex1  )) <1){
                        $this->SetTextColor('255','0','0');
                        $this->Cell(17, 8, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C'); 
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->Cell(17, 8, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C');                             
                        $this->SetTextColor('0','0','0');
                    }
                    $step1 = $step1 + (($rowm["cat11"]/$cat11)*$outof);
                    $step11 = $step11 + (($rowm["ex1"]/$ex1)*$outof);
                    //term 2
                    if(($rowm["cat22"]/$cat22) > 0.5){
                        $this->SetTextColor('0','0','0');
                        $this->Cell(15, 8, (($rowm["cat22"]/$cat22)*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('255','0','0');
                        $this->Cell(15, 8, (($rowm["cat22"]/$cat22)*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    if(($rowm["ex2"]  /$ex2  ) < 0.5){
                        $this->SetTextColor('255','0','0');
                        $this->Cell(15, 8, (($rowm["ex2"]  /$ex2  )*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->Cell(15, 8, (($rowm["ex2"]  /$ex2  )*$outof), 1, 0, 'C');
                        $this->SetTextColor('0','0','0');
                    }
                    if((($rowm["cat22"]/$cat22)+($rowm["ex2"]  /$ex2  )) <1){
                        $this->SetTextColor('255','0','0');
                        $this->Cell(17, 8, ((($rowm["cat22"]/$cat22)*$outof)+(($rowm["ex2"]  /$ex2  )*$outof)), 1, 0, 'C'); 
                        $this->SetTextColor('0','0','0');
                    }
                    else{
                        $this->SetTextColor('0','0','0');
                        $this->Cell(17, 8, ((($rowm["cat22"]/$cat22)*$outof)+(($rowm["ex2"]  /$ex2  )*$outof)), 1, 0, 'C');                             
                        $this->SetTextColor('0','0','0');
                    }
                    $step2 = $step2 + (($rowm["cat22"]/$cat22)*$outof);
                    $step22 = $step22 + (($rowm["ex2"]/$ex2)*$outof);
                    $this->Ln();

                }

                $this->SetFont('Times', 'B', 13);
                $this->Cell(51, 8, 'Total marks', 1, 0, 'L');

                $sql_total = "SELECT SUM(cat11 + ex1 + Cat22 + ex2 + cat33 + ex3) as total FROM marks WHERE /*term LIKE '%$term%' AND*/ class LIKE '%$class%' /*AND stid LIKE '%$ide%'*/";
                $result_total = $conn->query($sql_total);
                $row_total = mysqli_fetch_assoc($result_total);
                $total_marks = $row_total['total'];

                //for making total of assessments for astudent (not converted)
                $total_annual = "SELECT SUM(cat11) AS total1a , SUM(ex1) AS total1b, SUM(cat22) AS total2a, SUM(ex2) AS total2b, SUM(cat33) AS total3a, SUM(ex3) AS total3b FROM marks WHERE class = '$class' ";
                $quely = $conn->query($total_annual);
                $totalrows = mysqli_fetch_assoc($quely);
                $totals1a = $totalrows['total1a'];
                $totals1b = $totalrows['total1b'];
                $totals2a = $totalrows['total2a'];
                $totals2b = $totalrows['total2b'];
                $totals3a = $totalrows['total3a'];
                $totals3b = $totalrows['total3b'];

                $totale1a = $totale1a + $totals1a;
                $totale2a = $totale2a + $totals1b;
                $totale1b = $totale1b + $totals2a;
                $totale2b = $totale2b + $totals2b;
                $totale1c = $totale1c + $totals3a;
                $totale2c = $totale2c + $totals3b;
                
                //different from the top ones its for total marks for student in marks table not yet converted
                $totals_annual = "SELECT SUM(cat11) AS totals1a , SUM(ex1) AS totals1b, SUM(cat22) AS totals2a, SUM(ex2) AS totals2b, SUM(cat33) AS totals3a, SUM(ex3) AS totals3b FROM assessments WHERE class = '$class' ";
                $queby = $conn->query($totals_annual);
                $totalrows = mysqli_fetch_assoc($queby);
                $totalss1a = $totalrows['totals1a'];
                $totalss1b = $totalrows['totals1b'];
                $totalss2a = $totalrows['totals2a'];
                $totalss2b = $totalrows['totals2b'];
                $totalss3a = $totalrows['totals3a'];
                $totalss3b = $totalrows['totals3b'];

                $totalee1a = $totalss1a;
                $totalee2a = $totalss1b;
                $totalee1b = $totalss2a;
                $totalee2b = $totalss2b;
                $totalee1c = $totalss3a;
                $totalee2c = $totalss3b;

                //TOTAL MARKS
                $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid LIKE '%$ide%' ORDER BY subject DESC";
                $resultm = $conn->query($sqlm);
                $rowm = mysqli_fetch_assoc($resultm);

                $this->Cell(15, 8, $totale1, 1, 0, 'C');
                $this->Cell(15, 8, $totale2, 1, 0, 'C');
                $this->Cell(15, 8, ($totale1 + $totale2), 1, 0, 'C');

                //TERM 1
                if(($step1/$totale1)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(15, 8, $step1 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(15, 8, $step1 ,1, 0, 'C');
                }
                if(($step11/$totale2)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(15, 8, $step11 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(15, 8, $step11 ,1, 0, 'C');
                }
                $step111 = $step1 + $step11;
                if(($step111/$max)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(17, 8, $step111 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(17, 8, $step111 ,1, 0, 'C');
                }

                
                //TERM 2
                if(($step2/$totale1)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(15, 8, $step2 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(15, 8, $step2 ,1, 0, 'C');
                }
                if(($step22/$totale2)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(15, 8, $step22 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(15, 8, $step22 ,1, 0, 'C');
                }
                $step222 = $step2 + $step22;
                if(($step222/$max)<5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(17, 8, $step222 ,1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(17, 8, $step222 ,1, 0, 'C');
                }

                $this->Ln();

                $this->Cell(96, 8, 'Percentage', 1, 0, 'L');
                //TERM 1
                if(($step111/$max)<5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(47, 8, round((($step111/$max)*100),1).' /100', 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(47, 8, round((($step111/$max)*100),1).' /100', 1, 0, 'C');
                }
                //TERM 2
                if(($step222/$max)<5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(47, 8, round((($step222/$max)*100),1).' /100', 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(47, 8, round((($step222/$max)*100),1).' /100', 1, 0, 'C');
                }
                $this->Ln();

                // term 1 position
                $sql_position = "SELECT fname, SUM(cat11 + ex1) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total DESC";
                $result_position = $conn->query($sql_position);

                $position1 = 1;
                while ($row_position = mysqli_fetch_assoc($result_position)) {
                    if ($row_position['fname'] == $fname) {
                        break;
                    }
                    $position1++;
                }

                //term 2 position
                $sql_position = "SELECT fname, SUM(cat22 + ex2) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total DESC";
                $result_position = $conn->query($sql_position);

                $position2 = 1;
                while ($row_position = mysqli_fetch_assoc($result_position)) {
                    if ($row_position['fname'] == $fname) {
                        break;
                    }
                    $position2++;
                }

                //COUNT STUDENTS' TOTAL NUMBER
                $tot_students = "SELECT SUM(count) as count FROM students WHERE class = '$class' ";
                $dothis = $conn->query($tot_students);
                $prefinal = mysqli_fetch_assoc($dothis);
                $final = $prefinal['count'];

                $this->Cell(96, 8, 'Position', 1, 0, 'L');
                $this->Cell(47, 8, $position1.' /'. $final, 1, 0, 'C');
                $this->Cell(47, 8, $position2.' /'. $final, 1, 0, 'C');
                $this->ln();
                // $this->cell(184, 8, '' , 1, 0);
                // $this->ln();

                //ADDENDA ---
                // $this->Cell(90, 8, "Class Teacher's Remarks and Signature", 1, 0, 'L');
                // $this->Cell(47, 8, '', 1, 0, 'C');
                // $this->Cell(47, 8, '', 1, 0, 'C');
                // $this->ln();

                // $this->Cell(90, 8, "Parent's Signature", 1, 0, 'L');
                // $this->Cell(47, 8, '', 1, 0, 'C');
                // $this->Cell(47, 8, '', 1, 0, 'C');
                $this->ln();

                $this->setY(-127);
                $this->setX(10);
                $this->Rect(10, 170, 190, 20 );
                $this->cell(35, 20, 'BEHAVIOUR', 1, 0, 'C');
                $this->cell(31, 10, 'TOTAL', 1, 0, 'C');
                $this->cell(62, 10, 'Term I', 1, 0, 'C');
                $this->cell(62, 10, 'Term II', 1, 0, 'C');
                $this->setY(-117);
                $this->setX(45);

                $pull = "SELECT be1 , be2 , be3 FROM marks WHERE stid = '$item' ";
                $bisubizo = $conn->query($pull);
                $each = mysqli_fetch_assoc($bisubizo);
                $term1 = $each['be1'];
                $term2 = $each['be2'];
                $term3 = $each['be3']; 

                $this->cell(31, 10, '40', 1, 0, 'C');
                $this->cell(62, 10, $term1, 1, 0, 'C');
                $this->cell(62, 10, $term2, 1, 0, 'C');
                $this->Ln();
                $this->setY(-80);
                $this->setX(15);
                $this->Rect(10, 200, 190, 40 );
                $this->Text(20, 217, 'REMARKS');
                $this->Text(90, 217, 'DATE');
                $this->SetFont('Times', 'i', 13);
                $this->Text(75, 225, date("l M jS, Y"));  
                $this->SetFont('Times', 'b', 13);          
                $this->Text(140, 217, 'HEADMASTER');
                $this->SetFont('Times', 'i', 13);
                $this->Text(127, 225, 'TUMUKUNDE Monica Leonard');

                //DECISION
                if(($step222/$max)>0.5){
                    $this->Text(15, 225, 'Maintain your position');
                    $this->Ln();
                }
                elseif((($step222/$max)>0.4)&&(($step222/$max)<0.5)){
                    $this->Text(20, 225, 'Pay attention');
                    $this->Ln();
                }
                elseif(($step222/$max)<0.4){
                    $this->Text(15, 225, 'Hard work please');
                    $this->Ln();
                }

            }
        }



    // ANNUAL --------------------------------------------------    
    } elseif($term === "term 3"){
        foreach($ice as $item){
            $sql = "SELECT * FROM marks WHERE class LIKE '%$class%'  AND stid='$item'/*AND term LIKE '%$term%' */ GROUP BY fname ORDER BY SUM(cat33 + ex3) DESC";
            $result = $conn->query($sql);

            $query = "SELECT * FROM students WHERE class = '$class' AND id = '$item' ";
            $res = mysqli_query( $conn , $query );
            $rowa = mysqli_fetch_assoc($res);
            $ros = mysqli_num_rows($res);

            if (!$result) {
                die("Query failed: " . $conn->error);
            }

            // $toto = count($rowa);

        while ($row = mysqli_fetch_assoc($result)) {
            $this->AddPage('P', 'A4', 0);

            if($rowa['dir']=='default.png'){
                $this->SetFont('Times', 'B', 14);
                $this->Cell(160, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                $this->Cell(-24, 5, 'Class :', 0, 0, 'R');
                $this->SetFont('Times', 'I', 14);
                $this->Cell(80, 5, $class, 0, 0, 'L');
                $this->Ln();

                $this->SetFont('Times', 'B', 14);
                $this->Cell(160, 8, 'ES KANOMBE', 0, 0, 'C');
                $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                $this->SetFont('Times', 'I', 12);
                $this->Cell(80, 8, $term, 0, 0, 'L');
                $this->Ln();

                $this->SetFont('Times', 'B', 14);
                $this->Cell(160, 8, 'Tel: 0788875779', 0, 0, 'C');
                $this->SetFont('Times', 'B', 14);
                $this->Cell(-5, 8, 'Student name :', 0, 0, 'R');
                $this->SetFont('Times', 'I', 14);
                $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                $this->Ln();

                $fname = $row["fname"];
                $ide = $row["stid"];

                $this->SetFont('Times', 'B', 13);
                $this->Cell(160, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                $this->SetFont('Times', 'B', 14);
                $this->Cell(8, 8, 'Student reg number :', 0, 0, 'R');
                $this->SetFont('Times', 'I', 14);
                $this->Cell(80, 8, ($item), 0, 0, 'L');
                $this->Ln();
                $this->Ln();
            }

            else{
                $this->Image('passports/'.$rowa['dir'], 170, 10, 30, 30);
                $this->SetFont('Times', 'B', 10);
                $this->Cell(130, 5, 'REPUBLIC OF RWANDA', 0, 0, 'C');
                $this->SetTextColor('0','0','0');
                $this->Cell(-23, 5, 'Class :', 0, 0, 'R');
                $this->SetFont('Times', '', 10);
                $this->Cell(80, 5, $class, 0, 0, 'L');
                $this->Ln();

                $this->SetTextColor('0','0','0');
                $this->SetFont('Times', 'B', 10);
                $this->Cell(130, 8, 'ES KANOMBE', 0, 0, 'C');
                $this->Cell(-23, 8, 'Term :', 0, 0, 'R');
                $this->SetFont('Times', '', 10);
                $this->Cell(50, 8, $term, 0, 0, 'L');
                $this->Ln();

                $this->SetFont('Times', 'B', 10);
                $this->Cell(130, 8, 'Tel: 0788875779', 0, 0, 'C');
                $this->SetFont('Times', 'B', 10);
                $this->Cell(-10, 8, 'Student name :', 0, 0, 'R');
                $this->SetFont('Times', '', 10);
                $this->Cell(80, 8, ($row["fname"].' '.$row["lname"]), 0, 0, 'L');
                $this->Ln();

                $fname = $row["fname"];
                $ide = $row["stid"];

                $this->SetFont('Times', 'B', 10);
                $this->Cell(130, 8, 'Email: infoefotec@gmail.com', 0, 0, 'C');
                $this->SetFont('Times', 'B', 10);
                $this->Cell(-1, 8, 'Student reg number :', 0, 0, 'R');
                $this->SetFont('Times', '', 10);
                $this->Cell(50, 8, ($item), 0, 0, 'L');
                $this->Ln();
                $this->Ln();
            }

            $this->SetFont('Times', 'B', 14);
            $this->Cell(190, 10, "STUDENT'S ANNUAL REPORT", 1, 0, 'C');
            $this->Ln();
            $this->Ln();

            $this->SetFont('Times', 'B', 12);
            $this->Cell(66, 8, 'TOTAL', 1, 0, 'C');
            $this->Cell(31, 8, ' TERM 1 ', 1, 0, 'C');
            $this->Cell(31, 8, 'TERM 2', 1, 0, 'C');
            $this->Cell(31, 8, 'TERM 3', 1, 0, 'C');
            $this->Cell(31, 8, 'ANNUAL', 1, 0, 'C');
            $this->Ln();

            $this->SetFont('Times', 'B', 10);
            $this->Cell(38, 8, 'SUBJECTS', 1, 0, 'C');
            $this->Cell(9, 8, ' CAT ', 1, 0, 'C');
            $this->Cell(9, 8, ' EX ', 1, 0, 'C');
            $this->Cell(10, 8, ' TOT ', 1, 0, 'C');
            $this->Cell(10, 8, ' CAT1 ', 1, 0, 'C');
            $this->Cell(10, 8, ' EX1 ', 1, 0, 'C');
            $this->Cell(11, 8, ' TOT1 ', 1, 0, 'C');
            $this->Cell(10, 8, ' CAT2 ', 1, 0, 'C');
            $this->Cell(10, 8, ' EX2 ', 1, 0, 'C');
            $this->Cell(11, 8, ' TOT2 ', 1, 0, 'C');
            $this->Cell(10, 8, ' CAT3 ', 1, 0, 'C');
            $this->Cell(10, 8, ' EX3 ', 1, 0, 'C');
            $this->Cell(11, 8, ' TOT3 ', 1, 0, 'C');
            $this->Cell(10, 8, ' CAT ', 1, 0, 'C');
            $this->Cell(10, 8, ' EX ', 1, 0, 'C');
            $this->Cell(11, 8, ' TOT ', 1, 0, 'C');
            $this->Ln();

            $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid ='$ide' ORDER BY outof DESC";
            $resultm = $conn->query($sqlm);


            $totale1 = 0;
            $totale2 = 0;
            $totale1a = 0;
            $totale2a = 0;
            $totale1b = 0;
            $totale2b = 0;
            $totale1c = 0;
            $totale2c = 0;
            $step11 = 0;
            $step1 = 0;
            $step22 = 0;
            $step2 = 0;
            $step33 = 0;
            $step3 = 0;
            $stepff = 0;
            $stepf = 0;
            
            $funn = "SELECT * FROM assessments WHERE class='$class'/*AND term='$term'*/ ";
            $funn1 = $conn->query($funn);
            $fun2 = mysqli_fetch_array($funn1);

            while(($fun1 = mysqli_fetch_assoc($funn1))>0){
                $totale1 = $totale1 + $fun1["outof"];
                $totale2 = $totale2 + $fun1["outof"];
            }

            $max = $totale1 + $totale2;

            while ($rowm = mysqli_fetch_assoc($resultm)) {
                $subj = $rowm['subject'];
                $sub = "SELECT cat11, ex1 , cat22, ex2, cat33, ex3, outof FROM assessments WHERE subject ='$subj'";
                $get = $conn->query($sub);
                $subq = mysqli_fetch_assoc($get);
                $outof = $subq['outof'];
                $cat11 = $subq['cat11'];
                $ex1 = $subq['ex1'];
                $cat22 = $subq['cat22'];
                $ex2 = $subq['ex2'];
                $cat33 = $subq['cat33'];
                $ex3 = $subq['ex3'];

                $this->SetFont('Times', 'B', 13);
                $this->Cell(38, 8, ($rowm["subject"]), 1, 0, 'L');
                $this->Cell(9, 8, (($rowm["outof"])), 1, 0, 'C');
                $this->Cell(9, 8, ($rowm["outof"]), 1, 0, 'C');
                $this->Cell(10, 8, ($rowm["outof"] + $rowm["outof"]), 1, 0, 'C');
                $this->SetFont('Times', '', 12);

                //TERM 1
                if(($rowm["cat11"]/$cat11) > 0.5){
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["cat11"]/$cat11)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if(($rowm["ex1"]  /$ex1  ) < 0.5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["ex1"]  /$ex1  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if((($rowm["cat11"]/$cat11)+($rowm["ex1"]  /$ex1  )) <1){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(11, 8, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C'); 
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(11, 8, ((($rowm["cat11"]/$cat11)*$outof)+(($rowm["ex1"]  /$ex1  )*$outof)), 1, 0, 'C');                             
                    $this->SetTextColor('0','0','0');
                }
                $step1 = $step1 + (($rowm["cat11"]/$cat11)*$outof);
                $step11 = $step11 + (($rowm["ex1"]/$ex1)*$outof);
                //TERM 2
                if(($rowm["cat22"]/$cat22) > 0.5){
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["cat22"]/$cat22)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["cat22"]/$cat22)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if(($rowm["ex2"]  /$ex2  ) < 0.5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["ex2"]  /$ex2  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["ex2"]  /$ex2  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if((($rowm["cat22"]/$cat22)+($rowm["ex2"]  /$ex2  )) <1){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(11, 8, ((($rowm["cat22"]/$cat22)*$outof)+(($rowm["ex2"]  /$ex2  )*$outof)), 1, 0, 'C'); 
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(11, 8, ((($rowm["cat22"]/$cat22)*$outof)+(($rowm["ex2"]  /$ex2  )*$outof)), 1, 0, 'C');                             
                    $this->SetTextColor('0','0','0');
                }
                $step2 = $step2 + (($rowm["cat22"]/$cat22)*$outof);
                $step22 = $step22 + (($rowm["ex2"]/$ex2)*$outof);

                // TERM 3
                if(($rowm["cat33"]/$cat33) > 0.5){
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["cat33"]/$cat33)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["cat33"]/$cat33)*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if(($rowm["ex3"]  /$ex3  ) < 0.5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, (($rowm["ex3"]  /$ex3  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, (($rowm["ex3"]  /$ex3  )*$outof), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if((($rowm["cat33"]/$cat33)+($rowm["ex3"]  /$ex3  )) <1){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(11, 8, ((($rowm["cat33"]/$cat33)*$outof)+(($rowm["ex3"]  /$ex3  )*$outof)), 1, 0, 'C'); 
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(11, 8, ((($rowm["cat33"]/$cat33)*$outof)+(($rowm["eX3"]  /$ex3  )*$outof)), 1, 0, 'C');                             
                    $this->SetTextColor('0','0','0');
                }

                $step3 = $step3 + (($rowm["cat33"]/$cat33)*$outof);
                $step33 = $step33 + (($rowm["ex3"]/$ex3)*$outof);

                //ANNUAL
                if(((($rowm["cat11"]/$cat11)+($rowm["cat22"]/$cat22)+($rowm["cat33"] /$cat33))/3)<0.5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, round((((($rowm["cat11"]/$cat11)*$outof)+(($rowm["cat22"]/$cat22)*$outof)+(($rowm["cat33"] /$cat33)*$outof))/3),1), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, round((((($rowm["cat11"]/$cat11)*$outof)+(($rowm["cat22"]/$cat22)*$outof)+(($rowm["cat33"] /$cat33)*$outof))/3),1), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if(((($rowm["ex1"]/$ex1)+($rowm["ex1"]/$ex2)+($rowm["ex3"] /$ex3))/3)<0.5){
                    $this->SetTextColor('255','0','0');
                    $this->Cell(10, 8, round((((($rowm["ex1"]  /$ex1  )*$outof)+(($rowm["ex2"] /$ex2 )*$outof)+(($rowm["ex3"]  /$ex3)*$outof))/3),1), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->Cell(10, 8, round((((($rowm["ex1"]  /$ex1  )*$outof)+(($rowm["ex2"] /$ex2 )*$outof)+(($rowm["ex3"]  /$ex3)*$outof))/3),1), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                if((((($rowm["ex1"]/$ex1)+($rowm["ex1"]/$ex2)+($rowm["ex3"] /$ex3))/3)+((($rowm["cat11"]/$cat11)+($rowm["cat22"]/$cat22)+($rowm["cat33"] /$cat33))/3))<0.5){
                    $this->SetTextColor('255','0','0');
                    $this->cell(11, 8, (round((((($rowm["cat11"]/$cat11)*$outof)+(($rowm["cat22"]/$cat22)*$outof)+(($rowm["cat33"] /$cat33)*$outof))/3),1)+round((((($rowm["ex1"]  /$ex1  )*$outof)+(($rowm["ex2"] /$ex2 )*$outof)+(($rowm["ex3"]  /$ex3)*$outof))/3),1)), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                else{
                    $this->SetTextColor('0','0','0');
                    $this->cell(11, 8, (round((((($rowm["cat11"]/$cat11)*$outof)+(($rowm["cat22"]/$cat22)*$outof)+(($rowm["cat33"] /$cat33)*$outof))/3),1)+round((((($rowm["ex1"]  /$ex1  )*$outof)+(($rowm["ex2"] /$ex2 )*$outof)+(($rowm["ex3"]  /$ex3)*$outof))/3),1)), 1, 0, 'C');
                    $this->SetTextColor('0','0','0');
                }
                $stepf = $stepf + (round((((($rowm["cat11"]/$cat11)*$outof)+(($rowm["cat22"]/$cat22)*$outof)+(($rowm["cat33"] /$cat33)*$outof))/3),1));
                $stepff = $stepff + (round((((($rowm["ex1"]  /$ex1  )*$outof)+(($rowm["ex2"] /$ex2 )*$outof)+(($rowm["ex3"]  /$ex3)*$outof))/3),1));
                $this->Ln();
            }

            $this->SetFillColor(255, 0, 0);
            $this->cell(190, 8, '', 1, 0, 'C');
            $this->Ln();

            $this->SetFont('Times', 'B', 13);
            $this->Cell(35, 8, 'Total marks', 1, 0, 'L');

            $sql_total = "SELECT SUM(cat11 + ex1 + Cat22 + ex2 + cat33 + ex3) as total FROM marks WHERE /*term LIKE '%$term%' AND*/ class LIKE '%$class%' /*AND stid LIKE '%$ide%'*/";
            $result_total = $conn->query($sql_total);
            $row_total = mysqli_fetch_assoc($result_total);
            $total_marks = $row_total['total'];



            //for making total of assessments for astudent (not converted)
            $total_annual = "SELECT SUM(cat11) AS total1a , SUM(ex1) AS total1b, SUM(cat22) AS total2a, SUM(ex2) AS total2b, SUM(cat33) AS total3a, SUM(ex3) AS total3b FROM marks WHERE class = '$class' ";
            $quely = $conn->query($total_annual);
            $totalrows = mysqli_fetch_assoc($quely);
            $totals1a = $totalrows['total1a'];
            $totals1b = $totalrows['total1b'];
            $totals2a = $totalrows['total2a'];
            $totals2b = $totalrows['total2b'];
            $totals3a = $totalrows['total3a'];
            $totals3b = $totalrows['total3b'];

            $totale1a = $totale1a + $totals1a;
            $totale2a = $totale2a + $totals1b;
            $totale1b = $totale1b + $totals2a;
            $totale2b = $totale2b + $totals2b;
            $totale1c = $totale1c + $totals3a;
            $totale2c = $totale2c + $totals3b;
            
            //different from the top ones its for total marks for student in marks table not yet converted
            $totals_annual = "SELECT SUM(cat11) AS totals1a , SUM(ex1) AS totals1b, SUM(cat22) AS totals2a, SUM(ex2) AS totals2b, SUM(cat33) AS totals3a, SUM(ex3) AS totals3b FROM assessments WHERE class = '$class' ";
            $queby = $conn->query($totals_annual);
            $totalrows = mysqli_fetch_assoc($queby);
            $totalss1a = $totalrows['totals1a'];
            $totalss1b = $totalrows['totals1b'];
            $totalss2a = $totalrows['totals2a'];
            $totalss2b = $totalrows['totals2b'];
            $totalss3a = $totalrows['totals3a'];
            $totalss3b = $totalrows['totals3b'];

            $totalee1a = $totalss1a;
            $totalee2a = $totalss1b;
            $totalee1b = $totalss2a;
            $totalee2b = $totalss2b;
            $totalee1c = $totalss3a;
            $totalee2c = $totalss3b;

            $sqlm = "SELECT * FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid LIKE '%$ide%' ORDER BY subject DESC";
            $resultm = $conn->query($sqlm);
            $rowm = mysqli_fetch_assoc($resultm);

            $this->Cell(10, 8, $totale1, 1, 0, 'C');
            $this->Cell(10, 8, $totale2, 1, 0, 'C');
            $this->Cell(11, 8, ($totale1 + $totale2), 1, 0, 'C');

            //TOTAL MARKS

            //TERM 1
            if(($step1/$totale1)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step1 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step1 ,1, 0, 'C');
            }
            if(($step11/$totale2)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step11 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step11 ,1, 0, 'C');
            }
            $step111 = $step1 + $step11;
            if(($step111/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(11, 8, $step111 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(11, 8, $step111 ,1, 0, 'C');
            }

            
            //TERM 2
            if(($step2/$totale1)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step2 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step2 ,1, 0, 'C');
            }
            if(($step22/$totale2)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step22 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step22 ,1, 0, 'C');
            }
            $step222 = $step2 + $step22;
            if(($step222/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(11, 8, $step222 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(11, 8, $step222 ,1, 0, 'C');
            }

            //TERM 3
            if(($step3/$totale1)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step3 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step3 ,1, 0, 'C');
            }
            if(($step33/$totale2)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $step33 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $step33 ,1, 0, 'C');
            }
            $step333 = $step3 + $step33;
            if(($step333/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(11, 8, $step333 ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(11, 8, $step333 ,1, 0, 'C');
            }

            //ANNUAL
            if(($stepf/$totale1)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $stepf,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $stepf ,1, 0, 'C');
            }
            if(($stepff/$totale2)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(10, 8, $stepff ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(10, 8, $stepff ,1, 0, 'C');
            }
            $stepfff = $stepf + $stepff;
            if(($stepfff/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->cell(11, 8, $stepfff ,1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->cell(11, 8, $stepfff ,1, 0, 'C');
            }
            $this->Ln();

            //IN USE !!!!!!!!!!!!1

            $this->Cell(66, 8, 'Percentage', 1, 0, 'L');
            //TERM 1 %

            if(($step111/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->Cell(31, 8, round((($step111/$max)*100),1).' /100', 1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->Cell(31, 8, round((($step111/$max)*100),1).' /100', 1, 0, 'C');
            }
            //TERM 2 %
            
            if(($step111/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->Cell(31, 8, round((($step222/$max)*100),1).' /100', 1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->Cell(31, 8, round((($step222/$max)*100),1).' /100', 1, 0, 'C');
            }

            //TERM 3 %

            if(($step111/$max)<5){
                $this->SetTextColor('255','0','0');
                $this->Cell(31, 8, round((($step333/$max)*100),1).' /100', 1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->Cell(31, 8, round((($step333/$max)*100),1).' /100', 1, 0, 'C');
            }

            //ANNUAL %

            if(($stepfff/$max)<0.5){
                $this->SetTextColor('255','0','0');
                $this->Cell(31, 8, round((($stepfff/$max)*100),1).' /100', 1, 0, 'C');
                $this->SetTextColor('0','0','0');
            }
            else{
                $this->SetTextColor('0','0','0');
                $this->Cell(31, 8, round((($stepfff/$max)*100),1).' /100', 1, 0, 'C');
            }
            $this->Ln();

            $sql_position = "SELECT fname, SUM(cat11 + ex1) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' AND stid = '$ide' GROUP BY stid ORDER BY total DESC";
            $result_position = $conn->query($sql_position);

            $position1 = 1;
            while ($row_position = mysqli_fetch_assoc($result_position)) {
                if ($row_position['fname'] == $fname) {
                    break;
                }
                $position1++;
            }

            //term 2 position
            $sql_position = "SELECT fname, SUM(cat22 + ex2) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total ASC";
            $result_position = $conn->query($sql_position);

            $position2 = 1;
            while ($row_position = mysqli_fetch_assoc($result_position)) {
                if ($row_position['fname'] == $fname) {
                    break;
                }
                $position2++;
            }
            
            //term 3 position
            $sql_position = "SELECT fname, SUM(cat33 + ex3) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total DESC";
            $result_position = $conn->query($sql_position);

            $position = 1;
            while ($row_position = mysqli_fetch_assoc($result_position)) {
                if ($row_position['fname'] == $fname) {
                    break;
                }
                $position++;
            }

            //annual position
            $sql_position = "SELECT fname, SUM(cat11 + ex1 + cat22 + ex2 + cat33 + ex3) as total FROM marks WHERE /*term LIKE '%$term%' AND */ class LIKE '%$class%' GROUP BY fname ORDER BY total DESC";
            $result_position = $conn->query($sql_position);

            $position3 = 1;
            while ($row_position = mysqli_fetch_assoc($result_position)) {
                if ($row_position['fname'] == $fname) {
                    break;
                }
                $position3++;
            }

            $tot_students = "SELECT SUM(count) as count FROM students WHERE class = '$class' ";
            $dothis = $conn->query($tot_students);
            $prefinal = mysqli_fetch_assoc($dothis);
            $final = $prefinal['count'];

            //POSITION
            $this->Cell(66, 8, 'Position', 1, 0, 'L');
            $this->Cell(31, 8, $position1.' /'. $final, 1, 0, 'C');
            $this->Cell(31, 8, $position2.' /'. $final, 1, 0, 'C');
            $this->Cell(31, 8, $position.' /'. $final, 1, 0, 'C');
            $this->Cell(31, 8, $position3.' /'. $final , 1, 0, 'C');
            

            //BEHAVIOURS
            $this->setY(-127);
            $this->setX(10);
            $this->Rect(10, 170, 190, 20 );
            $this->cell(35, 20, 'BEHAVIOUR', 1, 0, 'C');
            $this->cell(31, 10, 'TOTAL', 1, 0, 'C');
            $this->cell(31, 10, 'Term I', 1, 0, 'C');
            $this->cell(31, 10, 'Term II', 1, 0, 'C');
            $this->cell(31, 10, 'Term III', 1, 0, 'C');
            $this->cell(31, 10, 'ANNUAL', 1, 0, 'C');
            $this->setY(-117);
            $this->setX(45);

            $pull = "SELECT be1 , be2 , be3 FROM marks WHERE stid = '$item' ";
            $bisubizo = $conn->query($pull);
            $each = mysqli_fetch_assoc($bisubizo);
            $term1 = $each['be1'];
            $term2 = $each['be2'];
            $term3 = $each['be3']; 

            $this->cell(31, 10, '40', 1, 0, 'C');
            $this->cell(31, 10, $term1, 1, 0, 'C');
            $this->cell(31, 10, $term2, 1, 0, 'C');
            $this->cell(31, 10, $term3, 1, 0, 'C');
            $this->cell(31, 10, (($term1+$term2+$term3)/3), 1, 0, 'C');
            $this->Ln();
            $this->setY(-80);
            $this->setX(15);
            $this->Rect(10, 200, 190, 40 );
            $this->Text(14, 207, 'DECISION');
            $this->Text(90, 217, 'DATE');
            $this->SetFont('Times', 'i', 13);
            $this->Text(75, 225, date("l M jS, Y"));  
            $this->SetFont('Times', 'b', 13);          
            $this->Text(140, 217, 'HEADMASTER');
            $this->SetFont('Times', 'i', 13);
            $this->Text(127, 225, 'TUMUKUNDE Monica Leonard');

            //DECISION
            if(($step111/$max)>0.5){
                $this->setY(-60);
                $this->cell(20, 0, 'Promoted', 0, 0, 'R');
                $this->Ln();
                $this->setY(-75);
                $this->setX(15);
                $this->cell(28, 0, 'Discontinued', 1, 1, 'L');
                $this->Ln();
                $this->setY(-70);
                $this->setX(15);
                $this->cell(35, 0, 'Advised to repeat', 1, 0, 'L');
                $this->Ln();
            }
            elseif((($step111/$max)>0.4)&&(($step111/$max)<0.5)){
                $this->cell(20, 0, 'Promoted', 1, 0, 'R');
                $this->Ln();
                $this->setY(-75);
                $this->setX(15);
                $this->cell(28, 0, 'Discontinued', 1, 1, 'L');
                $this->Ln();
                $this->setY(-70);
                $this->setX(15);
                $this->cell(35, 0, 'Advised to repeat', 0, 0, 'L');
                $this->Ln();
            }
            elseif(($step111/$max)<0.4){
                $this->cell(20, 0, 'Promoted', 1, 0, 'R');
                $this->Ln();
                $this->setY(-75);
                $this->setX(15);
                $this->cell(28, 0, 'Discontinued', 0, 1, 'L');
                $this->Ln();
                $this->setY(-70);
                $this->setX(15);
                $this->cell(35, 0, 'Advised to repeat', 1, 0, 'L');
                $this->Ln();
            }
        }
    }
}
        }
    }

    $pdf = new MyPDF();
    $pdf->AliasNbPages();
    $pdf->generateReport($class, $term, $ice, $conn);
    $pdf->Output();
//  }

$conn->close();
?>

